[font]
size = 12

  [font.normal]
  family = "Hasklig"
  style = "Light"

  [font.bold]
  family = "Hasklig"
  style = "Semibold"

  [font.italic]
  family = "Hasklig"
  style = "Light Italic"

  [font.bold_italic]
  family = "Hasklig"
  style = "Semibold Italic"

[bell]
duration = 50
color = "#ffffff"

[window]
decorations = "buttonless"
