#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config status_bar                   off
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          1
yabai -m config window_border_radius         0 # -0.5
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xff5963a2 # 0xff775759
yabai -m config normal_window_border_color   0xff000055 # 0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# exlude applications
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Sonos$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^1Password" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off

yabai -m config window_topmost on
