vim.cmd [[source ~/dotfiles/nvim/essential.vim]]
vim.cmd [[source ~/dotfiles/nvim/settings.vim]]
vim.cmd [[source ~/dotfiles/nvim/plugins.lua]]
vim.cmd [[source ~/dotfiles/nvim/plugins.vim]]
vim.cmd [[source ~/dotfiles/nvim/lsp.lua]]
vim.cmd [[source ~/dotfiles/nvim/mappings.vim]]
vim.cmd [[source ~/dotfiles/nvim/notes.vim]]
-- vim.cmd [[source ~/dotfiles/nvim/scala.lua]]
