# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7cda3da2-987b-44d6-a92e-3989880879c6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0012-0AB6";
      fsType = "vfat";
    };

  fileSystems."/home/johannes/storage" =
    { device = "/dev/disk/by-uuid/e1181b4e-e3b0-40a2-a5b3-db5554e1b62d";
      fsType = "ext4";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/e3606580-d598-437c-83e7-b43b3b517939"; }];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
